export const gConfig = {
  global: {
    siteName: "JORDSON",
    domain: "https//www.jordson.fr",
    email_admin: "andreleclercqpro@gmail.com",
    port: 4002,
  },
  db: {
    dbName: "jrd",
    publicCollections: ["pages"],
  },
  mail: {
    host: "smtp.mailtrap.io",
    port: 2525,
    user: "0b9dfe8ea837d1",
    pass: "c890421a8e87e1",
  },
  mimeTypes: {
    html: "text/html",
    js: "text/javascript",
    css: "text/css",
    json: "application/json",
    png: "image/png",
    jpg: "image/jpg",
    gif: "image/gif",
    svg: "image/svg+xml",
    wav: "audio/wav",
    mp4: "video/mp4",
    woff: "application/font-woff",
    ttf: "application/font-ttf",
    eot: "application/vnd.ms-fontobject",
    otf: "application/font-otf",
    wasm: "application/wasm",
  },
};
